set search_path = workspace;

CREATE TRIGGER fix_labor_legislation
AFTER INSERT ON Delivery_man
REFERENCING NEW TABLE AS NEW
FOR EACH STATEMENT
EXECUTE PROCEDURE check_birth_date();

CREATE TRIGGER discount_trigger
AFTER INSERT ON Operations
REFERENCING NEW TABLE AS NEW
FOR EACH STATEMENT
EXECUTE PROCEDURE apply_discount();
